#cloud:
#  aws:
#    credentials:
#      access-key: DO00MFHV7ZEZXWUGX6Y2
#      secret-key: L1t/CiYgSCau1Z1kjmiuxgUbHuMjO1y2vSzsXhqgTJk
#    region:
#      static: us-east-1
#    stack:
#      auto: false
#
#application:
#  bucket:
#    name: jobsbyus
#
#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB
#
#server:
#  port: 9090